---
- name: Install python
  hosts: bro-host
  gather_facts: no
  become: true

  pre_tasks:
    - name: check python availability
      raw: test -e /usr/bin/python
      register: test
      changed_when: false
      failed_when: false

    - name: install python-minimal package
      raw: sudo apt update && sudo apt install -y python-minimal
      when: test|failed

- name: Install docker and containers
  hosts: bro-host
  become: true
  roles:
   - {role: angstwad.docker_ubuntu, tags: ['docker', 'provision']}
   - {role: kamaln7.swapfile, tags: ['swapfile', 'provision']}
   - {role: ir4y.broserver, tags: ['broserver', 'provision']}

   - {role: ir4y.docker_app,
      name: 'hello-world',
      image: 'brogency/hello-world',
      server_name: '{{ lookup("env","SERVER_IP") }}',
      web_worker_count: 3,
      tags: ['hello-world']
   }
