---
- name: Create {{ name }} postgres user
  postgresql_user:
    login_host: 127.0.0.1
    login_unix_socket: no
    login_password: "{{ postgres_superuser_password }}"
    name: "{{ name }}"
    password: "{{ postgres_app_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
  when: use_postgres

- name: Create {{ name }} database
  postgresql_db:
    login_host: 127.0.0.1
    login_unix_socket: no
    login_password: "{{ postgres_superuser_password }}"
    name: "{{name}}"
    owner: "{{name}}"
    encoding: UTF-8
  when: use_postgres

- name: Run {{ name }} redis
  docker_container:
    name: "{{ name }}-redis"
    image: "{{ redis_image }}"
    restart_policy: always
  when: use_redis

- name: Run {{name}} web workers
  docker_container:
    name: "{{name}}-web-worker-{{item}}"
    image: "{{web_worker_image}}"
    restart_policy: always
    command: "{{ web_worker_command }}"
    env: "{{ default_env|merge(env)|merge(web_worker_env) }}"
  tags:
  - webworker
  - deploy
  with_sequence: count="{{web_worker_count}}"

- name: Run {{ name }} delay job workers
  docker_container:
    name: "{{ name }}-delay-job-worker"
    image: "{{ delay_job_worker_image }}"
    restart_policy: always
    command: "{{ delay_job_worker_command }}"
    env: "{{ default_env|merge(env)|merge(delay_job_worker_env) }}"
  tags:
  - delay_job_worker
  - deploy
  with_sequence: count="{{delay_job_worker_count}}"

- name: Configure balancer for {{ name }} web_worker
  etcd:
    state: present
    host: "{{ ansible_docker0['ipv4']['address'] }}"
    port: 4001
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - {key: "/hosts/{{ web_worker_base_name }}/enable", value: True}
  - {key: "/hosts/{{ web_worker_base_name }}/server_name", value: "{{server_name}}"}
  when: web_worker_count > 1
  tags:
  - etcd

- name: Setup nginx caching
  etcd:
    state: "present"
    host: "{{ ansible_docker0['ipv4']['address'] }}"
    port: 4001
    key: "/hosts/{{ web_worker_base_name }}/caches/{{ item.name }}/path"
    value: item.path
  with_items: "{{ caches }}"
  tags:
  - etcd
