---
use_postgres: true
postgres_superuser_password: "{{ lookup('password', 'password/db/postgres length=15') }}"
postgres_app_password: "{{ lookup('password', 'password/db/' + name + ' length=15') }}"

use_redis: false
redis_image: redis:3-alpine

web_worker_image: "{{image}}"
web_worker_base_name: "{{ image.split('/')[-1] }}"
web_worker_command: ""
web_worker_ports: []
web_worker_count: 1
web_worker_state: "reloaded"
web_worker_env: {}

delay_job_worker_image: "{{image}}"
delay_job_worker_command: "celery -B -A {{name}} worker"
delay_job_worker_count: 0
delay_job_worker_env: {}

default_env:
  DATABASE_URL: "postgres://{{name}}:{{postgres_app_password}}@db/{{name}}"
  REDIS_URL: "redis://{{name}}-redis/"
  DEBUG: False
env: {}

server_name: "{{ name }}.bro.engineering"

caches: {}
