- name: Create backupsrv users
  htpasswd:
    path: /home/backups/.htpasswd
    name: "{{ item }}"
    password: "{{ lookup('password', 'password/backupsrv/' + item + ' length=15') }}"
  with_items:
  - backupsrv
  tags:
  - backupsrv

- name: Setup web server for backups
  etcd:
    state: "present"
    host: "{{ ansible_docker0['ipv4']['address'] }}"
    port: 4001
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
  - {key: "/hosts/static/backupsrv/server_name", value: "{{ backup_server_name }}"}
  - {key: "/hosts/static/backupsrv/media", value: "/home/backups/"}
  - {key: "/hosts/static/backupsrv/private", value: True}
  tags:
  - backupsrv
