- name: Run etcd key value store
  docker_container:
    name: etcd
    image: quay.io/coreos/etcd:v2.3.8
    restart_policy: always
    command: '-name etcd-node1 --addr {{ ansible_docker0["ipv4"]["address"] }}:4001'
    ports:
    - '{{ ansible_docker0["ipv4"]["address"] }}:4001:4001'
    - '{{ ansible_docker0["ipv4"]["address"] }}:7001:7001'

- name: Run docker registrator
  docker_container:
    name: registrator
    image: gliderlabs/registrator:latest
    restart_policy: always
    command: '-internal etcd://{{ ansible_docker0["ipv4"]["address"] }}:4001/services'
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock

- name: Run balancer
  docker_container:
    name: balancer
    image: brogency/balancer
    restart_policy: always
    ports:
    - 80:80
    env:
      ETCD: '{{ ansible_docker0["ipv4"]["address"] }}:4001'
  tags:
  - balancer
