- name: Install system deps
  apt: name={{ item }} update_cache=yes
  with_items:
  - postgresql-client
  - python-psycopg2
  - curl

- name:  Install python deps
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
  - requests
  - python-etcd
  tags:
  - python-deps

- include: balancer.yml
- include: postgresql.yml
