- name: Create postgresql-server data container
  docker:
    name: postgres-data
    image: busybox
    state: present
    volumes:
    - /var/lib/postgresql/data

- name: Run postgresql-server
  docker:
    name: postgresql-server
    state: reloaded
    restart_policy: always
    image: postgres:9.4
    volumes_from:
    - postgres-data
    ports:
    - 127.0.0.1:5432:5432
    env:
      POSTGRES_PASSWORD: "{{ lookup('password', 'password/db/postgres length=15') }}"
  tags:
  - postgres

- wait_for: port=5432
